import type { Metadata } from 'next';
import { Inter, Ubuntu } from 'next/font/google';
import './globals.css';
import AppNavbar from '@/components/AppNavbar';

const inter = Ubuntu({ subsets: ['latin'], weight: '300' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.ico'
	}
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} dark flex flex-col min-h-screen`}>
				<AppNavbar />
				<div className='flex-grow'>
					{children}
				</div>
			</body>
		</html>
	)
}
